### ISSUE TITLE
Is this the codebase for https://arxiv.org/pdf/2006.08381.pdf?

### ISSUE THREAD

**Issue by jrb314** [ellisk42/ec#64]
Hi,

Is this the codebase for https://arxiv.org/pdf/2006.08381.pdf?  Great paper!!

I just did a git clone, got the requirements and tried to run:

python bin/list.py

but got:

Traceback (most recent call last):
  File "/root/ec/bin/../dreamcoder/enumeration.py", line 302, in solveForTask_ocaml
    response = json.loads(response.decode("utf-8"))
  File "/opt/conda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ec/bin/../dreamcoder/enumeration.py", line 238, in _f
    r = f(*a, **k)
  File "/root/ec/bin/../dreamcoder/enumeration.py", line 312, in solveForTask_ocaml
    assert False, "MAX RAISE"
AssertionError: MAX RAISE

Traceback (most recent call last):
  File "bin/list.py", line 19, in <module>
response: b''
error: None
    main(args)
  File "/root/ec/bin/../dreamcoder/domains/list/main.py", line 410, in main
    explorationCompression(baseGrammar, train, testingTasks=test, **args)
  File "/root/ec/bin/../dreamcoder/dreamcoder.py", line 129, in explorationCompression
message, {"DSL": {"logVariable": 0.0, "productions": [{"expression": "map", "logProbability": 0.0}, {"expression": "unfold", "logProbability": 0.0}, {"expression": "range", "logProbability": 0.0}, {"expression": "index", "logProbability": 0.0}, {"expression": "fold", "logProbability": 0.0}, {"expression": "length", "logProbability": 0.0}, {"expression": "if", "logProbability": 0.0}, {"expression": "+", "logProbability": 0.0}, {"expression": "-", "logProbability": 0.0}, {"expression": "empty", "logProbability": 0.0}, {"expression": "cons", "logProbability": 0.0}, {"expression": "car", "logProbability": 0.0}, {"expression": "cdr", "logProbability": 0.0}, {"expression": "empty?", "logProbability": 0.0}, {"expression": "0", "logProbability": 0.0}, {"expression": "1", "logProbability": 0.0}, {"expression": "*", "logProbability": 0.0}, {"expression": "mod", "logProbability": 0.0}, {"expression": "gt?", "logProbability": 0.0}, {"expression": "eq?", "logProbability": 0.0}, {"expression": "is-prime", "logProbability": 0.0}, {"expression": "is-square", "logProbability": 0.0}]}, "tasks": [{"examples": [{"inputs": [[[false, false, false], [false], [true], [true]]], "output": [[false, false, false], [false], [true], [true]]}, {"inputs": [[[false, true, false], [], [true, false, false], [true, false]]], "output": [[false, true, false], [true, false, false], [true, false]]}, {"inputs": [[[false], [], [true, true, true], [true]]], "output": [[false], [true, true, true], [true]]}, {"inputs": [[[], [true, false], [true, false], [true, true, false]]], "output": [[true, false], [true, false], [true, true, false]]}, {"inputs": [[[false], [], [false, false], [true, true, true]]], "output": [[false], [false, false], [true, true, true]]}, {"inputs": [[[false, true, true], [], [false, true], [true, false]]], "output": [[false, true, true], [false, true], [true, false]]}, {"inputs": [[[false, false, false], [false, true, true], [false, false, true], [false, true]]], "output": [[false, false, false], [false, true, true], [false, false, true], [false, true]]}, {"inputs": [[[true, true], [true], [true, true], []]], "output": [[true, true], [true], [true, true]]}, {"inputs": [[[], [true, true], [true, false], [false]]], "output": [[true, true], [true, false], [false]]}, {"inputs": [[[true], [], [true, true, false], [false, true]]], "output": [[true], [true, true, false], [false, true]]}, {"inputs": [[[true, true, true], [], [true, false], []]], "output": [[true, true, true], [true, false]]}, {"inputs": [[[], [true, true, false], [false], [false, true, false]]], "output": [[true, true, false], [false], [false, true, false]]}, {"inputs": [[[false], [true, false, true], [false, true, false], [false]]], "output": [[false], [true, false, true], [false, true, false], [false]]}, {"inputs": [[[false, false], [false], [], [false]]], "output": [[false, false], [false], [false]]}, {"inputs": [[[false, false, true], [true, true], [true], [false, true, true]]], "output": [[false, false, true], [true, true], [true], [false, true, true]]}], "name": "remove empty lists", "request": {"constructor": "->", "arguments": [{"constructor": "list", "arguments": [{"constructor": "list", "arguments": [{"constructor": "bool", "arguments": []}]}]}, {"constructor": "list", "arguments": [{"constructor": "list", "arguments": [{"constructor": "bool", "arguments": []}]}]}]}, "maximumFrontier": 10}], "programTimeout": 0.0005, "nc": 1, "timeout": 10.0, "lowerBound": 0.0, "upperBound": 1.5, "budgetIncrement": 1.5, "verbose": false, "shatter": 10}
    for r in ecIterator(*arguments, **keywords):
  File "/root/ec/bin/../dreamcoder/dreamcoder.py", line 407, in ecIterator
    evaluationTimeout=evaluationTimeout)
  File "/root/ec/bin/../dreamcoder/dreamcoder.py", line 553, in default_wake_generative
    evaluationTimeout=evaluationTimeout)
  File "/root/ec/bin/../dreamcoder/enumeration.py", line 186, in multicoreEnumeration
    assert False
AssertionError

Is the singularity method more recommended?

Thanks,
Ryan

**Comment by jrb314** [comment]
Maybe nevermind.  Got it working after installing these libs:
libzmq3-dev
libcairo2

Ryan
