### ISSUE TITLE
Error while following execution steps

### ISSUE THREAD

**Issue by Clarit7** [ellisk42/ec#80]
Thank you for providing nice implementation. However, I got stuck in executing basic test code and really want some helps.

```
PANIC! Exception in child worker: MAX RAISE
Traceback (most recent call last):
  File "/home/jaylee/Programming/ec/bin/../dreamcoder/enumeration.py", line 302, in solveForTask_ocaml
    response = json.loads(response.decode("utf-8"))
  File "/usr/local/conda/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/conda/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/conda/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaylee/Programming/ec/bin/../dreamcoder/enumeration.py", line 238, in _f
    r = f(*a, **k)
  File "/home/jaylee/Programming/ec/bin/../dreamcoder/enumeration.py", line 312, in solveForTask_ocaml
    assert False, "MAX RAISE"
AssertionError: MAX RAISE

Traceback (most recent call last):
  File "bin/list.py", line 19, in <module>
    main(args)
  File "/home/jaylee/Programming/ec/bin/../dreamcoder/domains/list/main.py", line 410, in main
    explorationCompression(baseGrammar, train, testingTasks=test, **args)
  File "/home/jaylee/Programming/ec/bin/../dreamcoder/dreamcoder.py", line 133, in explorationCompression
    for r in ecIterator(*arguments, **keywords):
  File "/home/jaylee/Programming/ec/bin/../dreamcoder/dreamcoder.py", line 406, in ecIterator
    topDownFrontiers, times = wake_generative(grammar, wakingTaskBatch,
  File "/home/jaylee/Programming/ec/bin/../dreamcoder/dreamcoder.py", line 552, in default_wake_generative
    topDownFrontiers, times = multicoreEnumeration(grammar, tasks,
  File "/home/jaylee/Programming/ec/bin/../dreamcoder/enumeration.py", line 186, in multicoreEnumeration
    assert False
AssertionError
```

I tried to execute bin/text.py in both of my own env(ubuntu 18.04 LTS) and singularity container env, but every time I got that error.
I also checked past issues: https://github.com/ellisk42/ec/issues/78 , https://github.com/ellisk42/ec/issues/64 .
None of them didn't works for me.
Do you have any idea about this error?

I use:
ubuntu 18.04 LTS
singularity 3.8.0
python 3.7.6

**Comment by Angular-Angel** [comment]
Which test code? Is this 'python text.py -t 20 -RS 5000' , or something else?

**Comment by Clarit7** [comment]
> Which test code? Is this 'python text.py -t 20 -RS 5000' , or something else?

The test code was 'python bin/text.py -t 20 -RS 5000'. I executed it in project root directory.

**Comment by Angular-Angel** [comment]
Hmm. yeah, that should have worked, so far as I can tell. I've encountered that same error you got when I was messing around trying to set up my own scripts, but I don't remember why or how I solved it.

**Comment by Angular-Angel** [comment]
Oh! Did you go through the steps to build the OCaml binaries? I think that was part of it.

**Comment by Clarit7** [comment]
> Oh! Did you go through the steps to build the OCaml binaries? I think that was part of it.

No I didn't. Thanks for advise. I'll try to build the OCaml binaries as you told. :)

**Comment by Angular-Angel** [comment]
Did that solve your issue? :0

**Comment by Clarit7** [comment]
> Did that solve your issue? :0

Your suggestion worked perfectly! Thank you!

**Comment by Angular-Angel** [comment]
Haha glad to hear it. Have you been able to get the program working generally? I was able to get the simple test demo working, and some other stuff, but I ran into a wall later: https://github.com/ellisk42/ec/issues/77

**Comment by Clarit7** [comment]
> Haha glad to hear it. Have you been able to get the program working generally? I was able to get the simple test demo working, and some other stuff, but I ran into a wall later: #77

I didn't tested yet with my own domain. I'll try it in the near future 👍

**Comment by Angular-Angel** [comment]
Awesome, thank you!

**Comment by evanthebouncy** [comment]
👍 🥳 🎉
